// Reviews Harvester · cron every 30 minutes
//
// Finds completed appointments older than `reviews_request_delay_min`
// (configurable in salon_settings, default 120) for which no
// review_requests row exists, the customer has marketing_consent, and
// the per-customer cooldown (default 90 days) has elapsed.
//
// For each match: insert a review_requests row (token generated by DB
// default), invoke notifications-router with eventType=review_request +
// the cuscinetto page URL (/recensione/{token}).
//
// Scheduled via:
//   supabase functions schedule reviews-harvester "*/30 * * * *"

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { corsHeaders } from '../_shared/cors.ts';
import { getSupabase } from '../_shared/supabaseAdmin.ts';

const EVENT_TYPE = 'review_request';
const SITE_URL = Deno.env.get('PUBLIC_SITE_URL') ?? 'https://hairrich.it';

interface Candidate {
  appointment_id: string;
  customer_id: string;
  first_name: string;
  completed_at: string;
  staff_name: string | null;
  service_name: string | null;
}

serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  const supabase = getSupabase();

  const { data: skill } = await supabase
    .from('skills_config')
    .select('enabled')
    .eq('skill_key', 'reviews_harvester')
    .maybeSingle();
  if (!skill?.enabled) {
    return ok({ skipped: true, reason: 'skill_disabled' });
  }

  const { data: candidates, error } = await supabase.rpc('fn_review_request_candidates', {
    p_limit: 25,
  });
  if (error) return fail(error.message);

  const list = (candidates ?? []) as Candidate[];
  const results: Array<{ appointment_id: string; status: string; token?: string; error?: string }> = [];

  for (const c of list) {
    const { data: inserted, error: insErr } = await supabase
      .from('review_requests')
      .insert({
        appointment_id: c.appointment_id,
        customer_id: c.customer_id,
        sent_via: 'email',
      })
      .select('id, token')
      .single();

    if (insErr || !inserted) {
      results.push({ appointment_id: c.appointment_id, status: 'insert_failed', error: insErr?.message });
      continue;
    }

    const link = `${SITE_URL}/recensione/${inserted.token}`;

    const { error: routerError } = await supabase.functions.invoke('notifications-router', {
      body: {
        mode: 'customer',
        customer_id: c.customer_id,
        event_type: EVENT_TYPE,
        payload: {
          first_name: c.first_name,
          link,
          staff_name: c.staff_name ?? '',
          service_name: c.service_name ?? '',
        },
      },
    });

    if (routerError) {
      results.push({
        appointment_id: c.appointment_id,
        status: 'router_failed',
        token: inserted.token,
        error: routerError.message,
      });
    } else {
      results.push({ appointment_id: c.appointment_id, status: 'sent', token: inserted.token });
    }
  }

  return ok({ ok: true, candidates: list.length, results });
});

function ok(body: unknown) {
  return new Response(JSON.stringify(body), {
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}

function fail(message: string) {
  return new Response(JSON.stringify({ ok: false, error: message }), {
    status: 500,
    headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  });
}
