// Skills Hub registry — metadata for all 101 digital "skills".
//
// The DB table skills_config stores ONLY enabled state + per-skill config
// JSONB. The friendly metadata (icon, italian name/description/example,
// effort estimate, category, etc.) lives here in code so a marketing copy
// change ships via a deploy, not a migration.
//
// Categories match the filter chips in /admin/funzionalita.

export type SkillCategory =
  | 'comunicazione'
  | 'booking'
  | 'ai'
  | 'analytics'
  | 'clienti'
  | 'team'
  | 'marketing'
  | 'vendite'
  | 'integrazioni'
  | 'avanzata';

export type SkillStatus =
  | 'recommended'       // ✅ promosso in CLAUDE.md — value/effort proven
  | 'available'         // ⏸️ utile, attiva quando vuoi
  | 'in_development'    // codice in corso, attiva quando ready
  | 'not_recommended';  // ❌ fuori scope per questo salone

export interface Skill {
  key: string;
  category: SkillCategory;
  icon: string;
  nameIT: string;
  descriptionIT: string;
  exampleIT?: string;
  benefitIT?: string;
  effortHours: number;
  monthlyCostEur: number;
  requiresAccount?: string[];
  relatedSkills?: string[];
  status: SkillStatus;
  alwaysOn?: boolean;            // gdpr_consents, admin_inbox — non disattivabile
}

export const SKILLS: Skill[] = [
  // ─── Comunicazione & Reminder ────────────────────────────────────────
  {
    key: 'whatsapp_reminders',
    category: 'comunicazione',
    icon: '💬',
    nameIT: 'Promemoria WhatsApp appuntamento',
    descriptionIT: 'Manda al cliente un promemoria su WhatsApp 24 ore e 2 ore prima del taglio. Costo zero, lettura quasi al 100%.',
    exampleIT: 'Marco prenota giovedì. Mercoledì sera riceve "Ciao Marco, ci vediamo domani alle 15:30?". Giovedì mattina alle 13:30 un nuovo ping.',
    benefitIT: 'Riduce le mancate presentazioni di circa il 25%',
    effortHours: 8,
    monthlyCostEur: 0,
    requiresAccount: ['WhatsApp Business API'],
    relatedSkills: ['sms_notifications', 'web_push', 'whatsapp_business_api'],
    status: 'recommended',
  },
  {
    key: 'sms_notifications',
    category: 'comunicazione',
    icon: '📩',
    nameIT: 'Notifiche SMS di backup',
    descriptionIT: 'Se il cliente non ha WhatsApp o non lo apre, mandagli un SMS. Costo basso (~€0,04 a SMS) ma arriva sempre.',
    benefitIT: 'Copre il ~10% di clienti senza WA attivo',
    effortHours: 4,
    monthlyCostEur: 5,
    requiresAccount: ['Twilio / Skebby'],
    relatedSkills: ['whatsapp_reminders'],
    status: 'available',
  },
  {
    key: 'renewal_reminders',
    category: 'comunicazione',
    icon: '🔄',
    nameIT: 'Promemoria rinnovo taglio',
    descriptionIT: 'Ogni 3-4 settimane dopo l\'ultimo taglio, un messaggio gentile: "Ci vediamo presto?". Mantiene il cliente in ciclo.',
    benefitIT: 'Aumenta la frequenza visite del 15-20%',
    effortHours: 6,
    monthlyCostEur: 0,
    relatedSkills: ['reactivation_campaigns', 'customer_segments'],
    status: 'available',
  },
  {
    key: 'birthday_campaign',
    category: 'comunicazione',
    icon: '🎂',
    nameIT: 'Auguri di compleanno automatici',
    descriptionIT: 'Ogni mattina alle 9 chi compie gli anni oggi riceve un messaggio con un regalo: coupon valido 7 giorni.',
    exampleIT: 'Oggi è il compleanno di Luca. Alle 9:00 riceve "Tanti auguri Luca! Un piccolo regalo: 20% sul prossimo taglio entro 7 giorni".',
    benefitIT: '80%+ di apertura messaggio, ~30% riscatta il coupon',
    effortHours: 3,
    monthlyCostEur: 0,
    relatedSkills: ['coupons', 'customer_onboarding', 'reactivation_campaigns'],
    status: 'recommended',
  },
  {
    key: 'reactivation_campaigns',
    category: 'comunicazione',
    icon: '🎯',
    nameIT: 'Campagne riattivazione clienti persi',
    descriptionIT: 'Settimanalmente identifica clienti che non vengono da >90 giorni e hanno fatto ≥2 visite. Manda un messaggio "Ti aspettiamo" + coupon. Tono empatico, mai invadente.',
    benefitIT: '~15% dei clienti contattati torna entro 30 giorni',
    effortHours: 5,
    monthlyCostEur: 0,
    relatedSkills: ['customer_segments', 'coupons', 'birthday_campaign'],
    status: 'recommended',
  },
  {
    key: 'last_minute_promo',
    category: 'comunicazione',
    icon: '📣',
    nameIT: 'Promo last-minute (manuale)',
    descriptionIT: 'Quando l\'agenda di domani ha buchi ricevi un alert Telegram. Tu decidi se attivare la promo: sconto max -15% solo per clienti abituali, max 1/mese a cliente.',
    exampleIT: 'Lunedì sera vedi che martedì hai 3 buchi. Tap "Attiva promo" → 12 clienti abituali ricevono "Domani slot libero alle 11, -15%".',
    benefitIT: 'Riempie il 60% dei buchi dell\'ultimo minuto senza svalutare i prezzi',
    effortHours: 6,
    monthlyCostEur: 0,
    relatedSkills: ['telegram_owner_alerts', 'customer_segments', 'coupons'],
    status: 'recommended',
  },
  {
    key: 'newsletter',
    category: 'comunicazione',
    icon: '💌',
    nameIT: 'Newsletter mensile',
    descriptionIT: 'Email mensile con novità, foto dei lavori, consigli di cura. Utile se vuoi raccontare il brand più che vendere.',
    benefitIT: 'Brand awareness — non aspettare conversioni dirette',
    effortHours: 4,
    monthlyCostEur: 0,
    relatedSkills: ['ai_content_generator'],
    status: 'available',
  },
  {
    key: 'seasonal_campaigns',
    category: 'comunicazione',
    icon: '🌱',
    nameIT: 'Campagne stagionali',
    descriptionIT: 'Natale, festa del papà, capodanno: messaggi con coupon a tema. Pre-configurate, basta accendere il flag.',
    benefitIT: '~5-10 prenotazioni extra per occasione',
    effortHours: 5,
    monthlyCostEur: 0,
    relatedSkills: ['coupons', 'newsletter'],
    status: 'available',
  },
  {
    key: 'web_push',
    category: 'comunicazione',
    icon: '🔔',
    nameIT: 'Notifiche push del browser',
    descriptionIT: 'Il cliente che ha aggiunto il sito a casa (PWA) può ricevere notifiche push silenziose: promemoria, slot last-minute. Gratis, ma copertura realistica 15-25% dei registrati.',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['whatsapp_reminders', 'customer_pwa'],
    status: 'recommended',
  },
  {
    key: 'whatsapp_business_api',
    category: 'comunicazione',
    icon: '✅',
    nameIT: 'WhatsApp Business API',
    descriptionIT: 'Il fondamento tecnico per i messaggi WA automatici. Verificare account Meta, ottenere numero, template messaggi approvati.',
    benefitIT: 'Sblocca tutto il canale WhatsApp (reminder, riattivazione, last-minute)',
    effortHours: 12,
    monthlyCostEur: 5,
    requiresAccount: ['Meta Business', 'WA Cloud API'],
    relatedSkills: ['whatsapp_reminders', 'reactivation_campaigns', 'last_minute_promo'],
    status: 'available',
  },

  // ─── Prenotazione & Booking ──────────────────────────────────────────
  {
    key: 'waitlist',
    category: 'booking',
    icon: '⏳',
    nameIT: 'Lista d\'attesa intelligente',
    descriptionIT: 'Quando uno slot si libera (cancellazione), il primo in lista riceve subito un avviso con link "Prendi questo slot". Tempo per confermare adattivo: più si avvicina la data, meno tempo.',
    exampleIT: 'Marco cancella per giovedì alle 15. Luca, che era in lista per quel giorno, riceve un messaggio: "Si è liberato giovedì alle 15. Confermi entro 2 ore?".',
    benefitIT: 'Recupera l\'80% delle cancellazioni → zero buchi in agenda',
    effortHours: 14,
    monthlyCostEur: 0,
    relatedSkills: ['whatsapp_reminders', 'telegram_owner_alerts'],
    status: 'recommended',
  },
  {
    key: 'qr_checkin',
    category: 'booking',
    icon: '📲',
    nameIT: 'Check-in con QR code',
    descriptionIT: 'Cliente arriva, scansiona QR sul bancone, l\'app conferma la presenza. Utile per saloni con flusso alto.',
    effortHours: 6,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'deposit_prepayment',
    category: 'booking',
    icon: '💳',
    nameIT: 'Deposito anticipato per combo',
    descriptionIT: 'Per appuntamenti lunghi (combo €30 da 60 min) richiede un acconto di €10 alla prenotazione. Riduce no-show del 70%.',
    effortHours: 12,
    monthlyCostEur: 0,
    requiresAccount: ['Stripe'],
    status: 'available',
  },
  {
    key: 'instagram_booking',
    category: 'booking',
    icon: '🤳',
    nameIT: 'Prenotazione da Instagram',
    descriptionIT: 'Link diretto in bio Instagram che apre il booking drawer. Già attivo.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'auto_quote',
    category: 'booking',
    icon: '💡',
    nameIT: 'Preventivo automatico',
    descriptionIT: 'Calcolatore prezzi per servizi complessi. Non rilevante per Hair Rich (3 SKU a prezzo fisso).',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'booking_chatbot',
    category: 'booking',
    icon: '💬',
    nameIT: 'Chatbot prenotazioni 24/7',
    descriptionIT: 'Bot conversazionale che prende prenotazioni fuori orario. "Voglio un taglio sabato pomeriggio" → propone slot disponibili.',
    benefitIT: '~5-8 prenotazioni notturne extra a settimana',
    effortHours: 16,
    monthlyCostEur: 3,
    requiresAccount: ['OpenAI API'],
    relatedSkills: ['ai_receptionist', 'whatsapp_quote_agent'],
    status: 'available',
  },
  {
    key: 'telegram_booking_bot',
    category: 'booking',
    icon: '📱',
    nameIT: 'Bot Telegram per prenotare',
    descriptionIT: 'Bot Telegram dedicato per i clienti. Utenza limitata in Sardegna, basso ROI per un barber.',
    effortHours: 10,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'whatsapp_quote_agent',
    category: 'booking',
    icon: '🤖',
    nameIT: 'Agente WhatsApp preventivi',
    descriptionIT: 'Risponde su WA con preventivi automatici. Non utile con prezzi fissi.',
    effortHours: 12,
    monthlyCostEur: 5,
    status: 'not_recommended',
  },
  {
    key: 'google_reserve',
    category: 'booking',
    icon: '🔗',
    nameIT: 'Prenota da Google Business',
    descriptionIT: 'Pulsante "Prenota" direttamente sul profilo Google del salone. Cliente vede info → prenota senza uscire da Google. Setup ~1-2 settimane (approvazione partner program).',
    benefitIT: 'Traffico free da Google Search e Maps, +30% prenotazioni dirette',
    effortHours: 8,
    monthlyCostEur: 0,
    requiresAccount: ['Google Reserve Partner'],
    status: 'recommended',
  },
  {
    key: 'booking_abandonment_analytics',
    category: 'booking',
    icon: '📊',
    nameIT: 'Analisi abbandono prenotazione',
    descriptionIT: 'Traccia chi apre il booking drawer ma non conferma. Permette di capire dove perdi clienti nel funnel.',
    effortHours: 6,
    monthlyCostEur: 0,
    relatedSkills: ['google_analytics'],
    status: 'available',
  },

  // ─── AI & Intelligenza ───────────────────────────────────────────────
  {
    key: 'ai_receptionist',
    category: 'ai',
    icon: '🤖',
    nameIT: 'Receptionist AI 24/7',
    descriptionIT: 'AI completa che gestisce richieste clienti su WhatsApp: prenota, sposta, risponde a FAQ. Alto valore, complesso.',
    effortHours: 30,
    monthlyCostEur: 10,
    requiresAccount: ['OpenAI', 'WhatsApp Business API'],
    relatedSkills: ['booking_chatbot', 'whatsapp_business_api'],
    status: 'available',
  },
  {
    key: 'telegram_assistant',
    category: 'ai',
    icon: '🤝',
    nameIT: 'Segretario Telegram (assistente titolare)',
    descriptionIT: 'Un assistente su Telegram che risponde alle tue domande sul salone: appuntamenti del giorno, quanto ha speso un cliente, quante scorte di un prodotto restano, chi deve ritirare un ordine, incassi del mese. Solo per il titolare.',
    exampleIT: 'Scrivi al bot "che appuntamenti ho oggi?" o "quanto ha speso Marco?" e ti risponde in pochi secondi con i dati reali del gestionale.',
    benefitIT: 'Il gestionale in tasca: chiedi a voce/chat invece di cercare tra le schermate',
    effortHours: 12,
    monthlyCostEur: 2,
    requiresAccount: ['OpenAI API', 'Telegram Bot Token'],
    relatedSkills: ['telegram_owner_alerts', 'ai_weekly_suggestions'],
    status: 'recommended',
  },
  {
    key: 'owner_daily_brief',
    category: 'ai',
    icon: '📋',
    nameIT: 'Brief giornaliero AI (chiusura)',
    descriptionIT: 'A fine turno il bot ti scrive per primo e ti fa il punto della giornata: si sono presentati tutti? hanno lavorato tutte le ore? è stato usato materiale che era in vendita? ci sono state spese straordinarie? Poi calcola l\'incasso della giornata e lo divide tra POS e contanti.',
    exampleIT: 'Alle 20:00 il bot: "Oggi 18 appuntamenti su 20 (2 no-show). Tutti presenti? Ore ok? Quanto POS e quanto contanti?". Tu rispondi e la giornata è chiusa e contabilizzata.',
    benefitIT: 'Contabilità giornaliera fatta in 2 minuti via chat, senza fogli o registri',
    effortHours: 16,
    monthlyCostEur: 1,
    requiresAccount: ['OpenAI API', 'Telegram Bot Token'],
    relatedSkills: ['telegram_assistant', 'expense_tracking', 'auto_clock_in'],
    status: 'recommended',
  },
  {
    key: 'owner_morning_digest',
    category: 'ai',
    icon: '🌅',
    nameIT: 'Resoconto mattutino + storia IG',
    descriptionIT: 'Ogni mattina, all\'apertura, ricevi gli appuntamenti della giornata. Se l\'agenda ha buchi, il bot ti suggerisce di fare una storia su Instagram per avvisare che ci sono posti liberi oggi.',
    exampleIT: 'Ore 9:00: "Oggi 5 appuntamenti, hai diversi slot liberi nel pomeriggio — fai una storia IG per riempirli?".',
    benefitIT: 'Parti informato e riempi i buchi dell\'agenda in tempo reale',
    effortHours: 6,
    monthlyCostEur: 0,
    requiresAccount: ['Telegram Bot Token'],
    relatedSkills: ['owner_daily_brief', 'telegram_owner_alerts'],
    status: 'recommended',
  },
  {
    key: 'expense_tracking',
    category: 'vendite',
    icon: '🧾',
    nameIT: 'Spese attività',
    descriptionIT: 'Registra le spese del salone per categoria — attrezzatura nuova, detergenti per pulire, merce, abbigliamento personalizzato, stipendio dipendente, spese straordinarie. Le puoi dire al bot ("oggi ho speso 120€ in attrezzatura") o inserirle dal gestionale.',
    exampleIT: 'Scrivi al bot "speso 45€ in detergenti" → finisce nelle spese del mese e abbassa il margine reale.',
    benefitIT: 'Sai davvero quanto guadagni: incassi meno spese, sempre aggiornato',
    effortHours: 8,
    monthlyCostEur: 0,
    requiresAccount: [],
    relatedSkills: ['owner_daily_brief', 'suppliers_directory'],
    status: 'recommended',
  },
  {
    key: 'stock_consumption',
    category: 'vendite',
    icon: '📦',
    nameIT: 'Consumo prodotti (uso interno)',
    descriptionIT: 'Quando usi in salone un prodotto che era in vendita (es. una cera in polvere finita oggi), lo scali dal magazzino come spesa e non come vendita: lo stock passa da 20 a 19, ma senza incasso. Così il magazzino e il margine restano veri.',
    exampleIT: 'Dici al bot "ho finito una cera in polvere usandola in salone" → stock -1, registrato come consumo (spesa), non come vendita.',
    benefitIT: 'Magazzino sempre corretto e costi dei materiali monitorati',
    effortHours: 8,
    monthlyCostEur: 0,
    requiresAccount: [],
    relatedSkills: ['stock_alerts', 'owner_daily_brief'],
    status: 'recommended',
  },
  {
    key: 'auto_clock_in',
    category: 'team',
    icon: '⏰',
    nameIT: 'Timbratura automatica apertura',
    descriptionIT: 'La mattina, all\'inizio del lavoro, il cartellino si timbra in automatico con il messaggio di apertura attività. La timbratura di uscita e le ore effettive si confermano nel brief di chiusura.',
    exampleIT: 'Ore 9:00 apertura: il sistema timbra "inizio attività" per lo staff in turno, senza che nessuno debba ricordarsene.',
    benefitIT: 'Niente timbrature dimenticate al mattino; ore di servizio tracciate',
    effortHours: 5,
    monthlyCostEur: 0,
    requiresAccount: [],
    relatedSkills: ['owner_daily_brief'],
    status: 'recommended',
  },
  {
    key: 'hair_consult_ai',
    category: 'ai',
    icon: '💇',
    nameIT: 'Consulenza capelli AI da foto',
    descriptionIT: 'Cliente carica foto → AI suggerisce taglio. Non rilevante per un barber con 3 SKU.',
    effortHours: 20,
    monthlyCostEur: 5,
    status: 'not_recommended',
  },
  {
    key: 'ai_weekly_suggestions',
    category: 'ai',
    icon: '🧠',
    nameIT: 'Suggerimenti AI settimanali',
    descriptionIT: 'Ogni lunedì alle 9 analizza i dati della settimana e ti manda 3-5 azioni operative concrete: "Cliente X non viene da 60gg, attiva campagna", "Lunedì sempre vuoto, considera promo".',
    benefitIT: 'Coach virtuale che ti fa vedere cose che non guarderesti',
    effortHours: 10,
    monthlyCostEur: 1,
    requiresAccount: ['OpenAI API'],
    relatedSkills: ['ai_monthly_report', 'bookings_drop_alert'],
    status: 'recommended',
  },
  {
    key: 'review_sentiment_analysis',
    category: 'ai',
    icon: '😊',
    nameIT: 'Analisi sentiment recensioni',
    descriptionIT: 'Estrae temi positivi/negativi dalle recensioni Google. "Il 70% loda la rasatura, il 15% lamenta l\'attesa".',
    effortHours: 8,
    monthlyCostEur: 1,
    relatedSkills: ['reviews_harvester'],
    status: 'available',
  },
  {
    key: 'ai_content_generator',
    category: 'ai',
    icon: '🎨',
    nameIT: 'Generatore caption Instagram',
    descriptionIT: 'Carichi foto di un lavoro → AI genera 3 caption + hashtag + miglior orario per postare. Risparmio 2h/settimana.',
    exampleIT: 'Carichi foto taglio fade. AI restituisce: "Mid fade nitido. Il classico che funziona sempre. #fade #barbershop #olbia". Best time: giovedì 19:00.',
    benefitIT: 'Risparmio 2h/sett. + più consistenza nel feed',
    effortHours: 8,
    monthlyCostEur: 1,
    requiresAccount: ['OpenAI API'],
    relatedSkills: ['ai_weekly_suggestions', 'ai_monthly_report'],
    status: 'recommended',
  },
  {
    key: 'voice_responder_ai',
    category: 'ai',
    icon: '🎙️',
    nameIT: 'Risponditore vocale AI',
    descriptionIT: 'Chiamate perse → SMS auto con link al booking. Twilio + AI.',
    effortHours: 12,
    monthlyCostEur: 8,
    requiresAccount: ['Twilio'],
    status: 'available',
  },
  {
    key: 'ai_content_calendar',
    category: 'ai',
    icon: '📆',
    nameIT: 'Calendario editoriale AI',
    descriptionIT: 'Pianifica i post Instagram del mese con AI. Strumenti tipo Hootsuite fanno già 80% gratis.',
    effortHours: 16,
    monthlyCostEur: 5,
    status: 'available',
  },
  {
    key: 'demand_forecast',
    category: 'ai',
    icon: '📈',
    nameIT: 'Previsione domanda',
    descriptionIT: 'Predice quali giorni saranno pieni/vuoti nelle prossime 2 settimane. Aiuta a pianificare promo e turni.',
    effortHours: 14,
    monthlyCostEur: 0,
    relatedSkills: ['peak_hours_analysis', 'staff_shifts'],
    status: 'available',
  },
  {
    key: 'ai_price_optimizer',
    category: 'ai',
    icon: '💰',
    nameIT: 'Ottimizzatore prezzi AI',
    descriptionIT: 'Suggerisce variazioni prezzo basate sulla domanda. Irrilevante con prezzi fissi.',
    effortHours: 12,
    monthlyCostEur: 2,
    status: 'not_recommended',
  },
  {
    key: 'instagram_dm_chatbot',
    category: 'ai',
    icon: '💬',
    nameIT: 'Chatbot Instagram DM',
    descriptionIT: 'Risponde ai DM Instagram con info salone, prezzi, prenotazione. Utile per i leads social.',
    effortHours: 14,
    monthlyCostEur: 3,
    requiresAccount: ['Meta API'],
    status: 'available',
  },

  // ─── Analytics & Report ──────────────────────────────────────────────
  {
    key: 'ai_monthly_report',
    category: 'analytics',
    icon: '📊',
    nameIT: 'Report mensile AI',
    descriptionIT: 'Il 1° del mese alle 9 ricevi via email un report dettagliato del mese precedente: KPI, trend, top servizi, top operatori, obiettivi per il mese in corso. Generato da AI in linguaggio naturale.',
    exampleIT: '"Marzo: 187 appuntamenti (+12% vs feb), incasso €4.250. Top servizio: taglio classico (108). No-show: 3 (-50% vs feb). Obiettivo aprile: +15 nuovi clienti."',
    effortHours: 10,
    monthlyCostEur: 1,
    requiresAccount: ['OpenAI API'],
    relatedSkills: ['ai_weekly_suggestions', 'statistiche'],
    status: 'recommended',
  },
  {
    key: 'staff_performance_report',
    category: 'analytics',
    icon: '📈',
    nameIT: 'Performance per operatore',
    descriptionIT: 'Dashboard con appuntamenti, incasso, recensioni medie per ogni operatore. Su /admin/statistiche.',
    effortHours: 6,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'staff_leaderboard',
    category: 'analytics',
    icon: '🏆',
    nameIT: 'Classifica operatori',
    descriptionIT: 'Gamification per il team: classifica mensile per visite, recensioni, upsell. Motivazione interna.',
    effortHours: 5,
    monthlyCostEur: 0,
    relatedSkills: ['staff_performance_report'],
    status: 'available',
  },
  {
    key: 'customer_heatmap',
    category: 'analytics',
    icon: '🗺️',
    nameIT: 'Mappa di calore clienti',
    descriptionIT: 'Mostra da che zone di Olbia vengono i clienti. Utile per capire dove distribuire volantini.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'tax_quarterly_report',
    category: 'analytics',
    icon: '🧮',
    nameIT: 'Report fiscale trimestrale',
    descriptionIT: 'CSV con incassi, IVA e dettagli per il commercialista. Esporta in 1 click.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'bookings_drop_alert',
    category: 'analytics',
    icon: '📉',
    nameIT: 'Alert calo prenotazioni',
    descriptionIT: 'Lunedì 09:00: se le prenotazioni della settimana corrente sono >20% sotto la media delle 8 settimane precedenti, ricevi un alert Telegram con azioni suggerite (attiva promo, lancia win-back).',
    benefitIT: 'Sistema di allerta precoce — vedi il calo prima che diventi crisi',
    effortHours: 6,
    monthlyCostEur: 0,
    relatedSkills: ['telegram_owner_alerts', 'reactivation_campaigns', 'last_minute_promo'],
    status: 'recommended',
  },
  {
    key: 'peak_hours_analysis',
    category: 'analytics',
    icon: '⏰',
    nameIT: 'Orari di punta',
    descriptionIT: 'Heatmap delle ore più richieste per giorno della settimana. Aiuta a pianificare turni.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'utm_tracking',
    category: 'analytics',
    icon: '📡',
    nameIT: 'Tracking UTM campagne',
    descriptionIT: 'Sapere da quale link/QR è arrivata ogni prenotazione (volantino A, post Instagram B, ecc).',
    effortHours: 5,
    monthlyCostEur: 0,
    relatedSkills: ['qr_promotions', 'google_analytics'],
    status: 'available',
  },
  {
    key: 'google_analytics',
    category: 'analytics',
    icon: '📊',
    nameIT: 'Integrazione Google Analytics 4',
    descriptionIT: 'Tracking visite sito, comportamento, conversioni. Da configurare con GA4 e Search Console.',
    effortHours: 4,
    monthlyCostEur: 0,
    requiresAccount: ['GA4'],
    status: 'available',
  },
  {
    key: 'revenue_forecast',
    category: 'analytics',
    icon: '💹',
    nameIT: 'Previsione incasso mensile',
    descriptionIT: 'Proiezione fine mese basata su agenda confermata + trend storico.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'available',
  },

  // ─── Gestione Clienti ────────────────────────────────────────────────
  {
    key: 'customer_technical_sheet',
    category: 'clienti',
    icon: '📝',
    nameIT: 'Scheda tecnica cliente',
    descriptionIT: 'Formula colore, allergie, preferenze chimiche. Rilevante per parrucchieri donna, non per barber.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'loyalty',
    category: 'clienti',
    icon: '🎟️',
    nameIT: 'Fidelity & punti',
    descriptionIT: 'Sistema fedeltà configurabile (a timbri, a punti, cashback). Dopo X visite il cliente sblocca un premio. Tutte le regole modificabili dal gestionale.',
    exampleIT: 'Marco fa 5 tagli → 1 taglio gratis. Oppure: ogni €10 spesi = 1 punto, 50 punti = barba gratis.',
    benefitIT: 'Aumenta la frequenza visite e premia gli abituali',
    effortHours: 14,
    monthlyCostEur: 0,
    relatedSkills: ['coupons', 'referrals'],
    status: 'recommended',
  },
  {
    key: 'service_packages',
    category: 'clienti',
    icon: '🎫',
    nameIT: 'Pacchetti prepagati (5-10 tagli)',
    descriptionIT: 'Vendi pacchetti tipo "10 tagli a €180" in salone. Il cliente paga cash/POS, riceve email ricevuta, e a ogni prenotazione successiva usa un credito. Coerente con la filosofia "no online payment".',
    benefitIT: 'Cash flow anticipato + fedeltà bloccata per mesi',
    effortHours: 10,
    monthlyCostEur: 0,
    relatedSkills: ['loyalty', 'coupons'],
    status: 'recommended',
  },
  {
    key: 'gift_cards',
    category: 'clienti',
    icon: '🎁',
    nameIT: 'Gift card digitali',
    descriptionIT: 'Il cliente regala un voucher digitale a un amico. PDF stampabile + codice.',
    effortHours: 12,
    monthlyCostEur: 0,
    requiresAccount: ['Stripe'],
    relatedSkills: ['coupons'],
    status: 'available',
  },
  {
    key: 'coupons',
    category: 'clienti',
    icon: '🎪',
    nameIT: 'Coupon e sconti',
    descriptionIT: 'Sistema coupon completo: crea codici, validità, soglie, una tantum o ricorrenti. Quando attivo, il booking drawer mostra il campo "Hai un codice?".',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['birthday_campaign', 'reactivation_campaigns', 'qr_promotions'],
    status: 'recommended',
  },
  {
    key: 'noshow_outreach',
    category: 'clienti',
    icon: '🤝',
    nameIT: 'Gestione no-show empatica',
    descriptionIT: 'Mai blocchi automatici. Dashboard con clienti no-show + badge soft (🟡🟠🔴). Quando vuoi, click "Chiedi spiegazione" → AI scrive bozza empatica ("tutto bene? posso aiutarti?") che tu editi e invii.',
    benefitIT: 'Recupera clienti invece di perderli',
    effortHours: 10,
    monthlyCostEur: 0,
    relatedSkills: ['customer_segments'],
    status: 'recommended',
  },
  {
    key: 'gdpr_consents',
    category: 'clienti',
    icon: '🔐',
    nameIT: 'Consensi GDPR',
    descriptionIT: 'Sistema completo consensi separati (marketing, reminder, foto, profilazione, referral). Salvataggio firmato con timestamp + IP + versione policy. Revoca self-service. Obbligo legale Italia.',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['customer_onboarding', 'activity_log'],
    status: 'recommended',
    alwaysOn: true,
  },
  {
    key: 'customer_photos_archive',
    category: 'clienti',
    icon: '📸',
    nameIT: 'Archivio foto clienti pre/post',
    descriptionIT: 'Carica foto del lavoro su ogni appuntamento. Il cliente le rivede in /profilo e può condividerle.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'allergens_management',
    category: 'clienti',
    icon: '⚠️',
    nameIT: 'Gestione allergie',
    descriptionIT: 'Tag allergie chimiche per cliente. Non rilevante per barber con servizi base.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'customer_segments',
    category: 'clienti',
    icon: '🏷️',
    nameIT: 'Segmentazione clienti',
    descriptionIT: 'Etichette automatiche (cron daily) + manuali (max 5/cliente). Auto: 🆕Nuovo · 🔁Abituale · 💎VIP · 😴A rischio · 🚪Perso · ⚠️No-show · 🎂Compleanno mese · 🌍Turista · 🎁Referral. Soglie configurabili.',
    benefitIT: 'Foundation per campagne mirate (#4, #5, #6) — target chirurgico invece di blast generico',
    effortHours: 12,
    monthlyCostEur: 0,
    relatedSkills: ['reactivation_campaigns', 'birthday_campaign', 'last_minute_promo', 'advanced_customer_search'],
    status: 'recommended',
  },

  // ─── Gestione Team ───────────────────────────────────────────────────
  {
    key: 'staff_shifts',
    category: 'team',
    icon: '🕐',
    nameIT: 'Orari operatori',
    descriptionIT: 'Definisci turni settimanali per ogni operatore. Il booking engine rispetta gli orari.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'staff_gcal_sync',
    category: 'team',
    icon: '📅',
    nameIT: 'Sync Google Calendar staff',
    descriptionIT: 'Ogni operatore connette il proprio Google Calendar personale (OAuth). Sync bidirezionale: appuntamenti Hair Rich appaiono nel calendar personale; eventi "occupato" creati nel calendar personale bloccano slot booking.',
    benefitIT: 'Niente doppie prenotazioni con impegni privati',
    effortHours: 14,
    monthlyCostEur: 0,
    requiresAccount: ['Google Calendar'],
    status: 'recommended',
  },
  {
    key: 'agenda_pdf_print',
    category: 'team',
    icon: '🖨️',
    nameIT: 'Stampa agenda giornaliera PDF',
    descriptionIT: 'Esporta l\'agenda del giorno in PDF stampabile. Utile per chi preferisce la carta.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'staff_earnings_simulator',
    category: 'team',
    icon: '💰',
    nameIT: 'Simulatore guadagno operatore',
    descriptionIT: 'Mostra all\'operatore quanto sta guadagnando in base alle commissioni.',
    effortHours: 6,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'staff_permissions',
    category: 'team',
    icon: '🔑',
    nameIT: 'Permessi granulari operatori',
    descriptionIT: 'Definisci cosa può fare ogni operatore (vede/non vede prezzi altrui, può cancellare, ecc).',
    effortHours: 10,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'staff_mobile_dashboard',
    category: 'team',
    icon: '📱',
    nameIT: 'Dashboard mobile operatore',
    descriptionIT: 'App PWA dedicata staff con solo i suoi appuntamenti. Sito admin attuale è già mobile-responsive.',
    effortHours: 12,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'staff_auto_onboarding',
    category: 'team',
    icon: '⚙️',
    nameIT: 'Onboarding operatore automatico',
    descriptionIT: 'Wizard 4 step per nuovi operatori: dati, orari, servizi, foto profilo.',
    effortHours: 6,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'activity_log',
    category: 'team',
    icon: '📋',
    nameIT: 'Log attività gestionale',
    descriptionIT: 'Traccia ogni modifica fatta nel gestionale (chi/cosa/quando, con diff). Visibile in /admin/log con filtri, diff viewer, export CSV. Sub-config: retention, alert critici, visibilità per-staff.',
    benefitIT: 'Trasparenza interna + traccia per dispute',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['gdpr_consents'],
    status: 'recommended',
  },
  {
    key: 'vacation_calendar',
    category: 'team',
    icon: '📆',
    nameIT: 'Calendario ferie',
    descriptionIT: 'Gestisci chiusure straordinarie e ferie staff. Già attivo (chiusure.tsx).',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'team_internal_chat',
    category: 'team',
    icon: '💬',
    nameIT: 'Chat interna team',
    descriptionIT: 'WhatsApp/Telegram esterno fanno meglio per un team piccolo.',
    effortHours: 12,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },

  // ─── Marketing & Social ──────────────────────────────────────────────
  {
    key: 'social_scheduler',
    category: 'marketing',
    icon: '📱',
    nameIT: 'Scheduler social',
    descriptionIT: 'Pubblica automaticamente su Instagram/Facebook. Buffer e Later sono gratis e fanno meglio.',
    effortHours: 14,
    monthlyCostEur: 5,
    status: 'not_recommended',
  },
  {
    key: 'reviews_harvester',
    category: 'marketing',
    icon: '⭐',
    nameIT: 'Raccolta automatica recensioni Google',
    descriptionIT: 'Dopo ogni appuntamento concluso, manda al cliente un messaggio per chiedergli di lasciare una recensione. I clienti felici li dirotta su Google, quelli scontenti su un canale interno (per non rovinare la media).',
    exampleIT: 'Marco esce alle 14. Alle 16:30 riceve "Com\'è andata oggi?". Tap su 😊 → Google con recensione pre-compilata. Tap su 😞 → arriva un alert a te (NON va su Google).',
    benefitIT: 'Da 4.2 a 4.7 stelle in 3 mesi = +30% click dal profilo Google',
    effortHours: 14,
    monthlyCostEur: 0,
    requiresAccount: ['Google Place ID'],
    relatedSkills: ['post_visit_survey', 'telegram_owner_alerts'],
    status: 'recommended',
  },
  {
    key: 'video_testimonials',
    category: 'marketing',
    icon: '🗣️',
    nameIT: 'Raccolta video testimonianze',
    descriptionIT: 'Form per upload video recensione. Mostrali in homepage.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'before_after_gallery',
    category: 'marketing',
    icon: '📸',
    nameIT: 'Gallery before/after',
    descriptionIT: 'Slider con foto prima/dopo. Già attivo in /lavori.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'referrals',
    category: 'marketing',
    icon: '🤝',
    nameIT: 'Programma referral (porta-un-amico)',
    descriptionIT: 'Ogni cliente ha un codice unico. Lo condivide. Quando l\'amico prenota e viene, entrambi ricevono un credito. Tracking conversioni e leaderboard.',
    benefitIT: 'Ogni cliente attivo può portarti 1-2 clienti/anno',
    effortHours: 12,
    monthlyCostEur: 0,
    relatedSkills: ['coupons', 'loyalty'],
    status: 'recommended',
  },
  {
    key: 'meta_ads_integration',
    category: 'marketing',
    icon: '📡',
    nameIT: 'Meta Ads (FB/IG)',
    descriptionIT: 'Pixel + Conversion API per tracciare conversioni delle inserzioni a pagamento.',
    effortHours: 8,
    monthlyCostEur: 0,
    requiresAccount: ['Meta Business'],
    status: 'available',
  },
  {
    key: 'social_comment_bot',
    category: 'marketing',
    icon: '💬',
    nameIT: 'Bot risposta commenti social',
    descriptionIT: 'Risponde automaticamente ai commenti sotto i post Instagram/FB. Edge case, alta complessità.',
    effortHours: 14,
    monthlyCostEur: 5,
    status: 'not_recommended',
  },
  {
    key: 'dynamic_link_in_bio',
    category: 'marketing',
    icon: '🔗',
    nameIT: 'Link in bio dinamico',
    descriptionIT: 'Il sito stesso funziona da link-in-bio aggiornato dal database. Già attivo.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'tiktok_integration',
    category: 'marketing',
    icon: '📱',
    nameIT: 'Integrazione TikTok',
    descriptionIT: 'TikTok Pixel + tracking. Utile se vuoi puntare a un pubblico giovane.',
    effortHours: 6,
    monthlyCostEur: 0,
    requiresAccount: ['TikTok for Business'],
    status: 'available',
  },
  {
    key: 'telegram_owner_alerts',
    category: 'marketing',
    icon: '📲',
    nameIT: 'Alert Telegram al titolare',
    descriptionIT: 'Bot Telegram dedicato che ti notifica eventi operativi: nuova prenotazione, cancellazione, recensione negativa, no-show, slot vuoto, alert calo, daily digest. Quali eventi vuoi è configurabile granulare. Costo €0. Setup 5 min.',
    benefitIT: 'Sai cosa succede in tempo reale senza aprire l\'admin',
    effortHours: 6,
    monthlyCostEur: 0,
    requiresAccount: ['Telegram Bot Token'],
    relatedSkills: ['admin_inbox', 'bookings_drop_alert'],
    status: 'recommended',
  },

  // ─── Vendite & Revenue ───────────────────────────────────────────────
  {
    key: 'smart_upsell',
    category: 'vendite',
    icon: '🛒',
    nameIT: 'Upsell intelligente',
    descriptionIT: 'Step opzionale prima della conferma in BookingDrawer: se cliente sta prenotando solo taglio → propone "Aggiungi barba +€10?". Max 1 upsell per booking. Dismiss permanente per chi dice "no grazie 3 volte".',
    benefitIT: '+20% AOV (Average Order Value) stimato',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'post_visit_survey',
    category: 'vendite',
    icon: '📋',
    nameIT: 'Sondaggio post-visita privato',
    descriptionIT: '2 ore dopo l\'appuntamento: email/Telegram con 3 emoji 😊😐😞 + campo libero opzionale. Resta PRIVATO (non va su Google) — serve a intercettare insoddisfazioni prima che diventino recensioni pubbliche. Separato da reviews_harvester.',
    benefitIT: 'NPS interno + early warning per problemi qualità',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['reviews_harvester', 'noshow_outreach'],
    status: 'recommended',
  },
  {
    key: 'credit_recovery_bot',
    category: 'vendite',
    icon: '💸',
    nameIT: 'Bot recupero crediti',
    descriptionIT: 'Insoluti, pagamenti scaduti. Un barber non ne ha tipicamente.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'seasonal_pricing',
    category: 'vendite',
    icon: '📅',
    nameIT: 'Listino stagionale',
    descriptionIT: 'Variazione prezzi per stagione/giorno. Non applicabile con prezzi fissi.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'stock_alerts',
    category: 'vendite',
    icon: '📦',
    nameIT: 'Alert scorte basse',
    descriptionIT: 'Soglie configurabili per prodotto. Cron daily 08:00: se prodotto sotto soglia → alert Telegram con trend velocità vendite + suggerimento quantità riordino. Pagina prodotti estesa con barra progresso e quick action "Riordina".',
    benefitIT: 'Mai più "ho finito lo shampoo X"',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['suppliers_directory', 'telegram_owner_alerts'],
    status: 'recommended',
  },
  {
    key: 'suppliers_directory',
    category: 'vendite',
    icon: '🏠',
    nameIT: 'Rubrica fornitori',
    descriptionIT: 'Database fornitori con contatti completi, termini di pagamento, storico ordini. Quick action "Nuovo ordine" che genera PDF bozza con quantità suggerite (basato su stock + velocità vendite).',
    effortHours: 10,
    monthlyCostEur: 0,
    relatedSkills: ['stock_alerts'],
    status: 'recommended',
  },
  {
    key: 'equipment_maintenance',
    category: 'vendite',
    icon: '🛠️',
    nameIT: 'Manutenzione attrezzature',
    descriptionIT: 'Checklist e reminder per pulizia/manutenzione attrezzi. Minor utility.',
    effortHours: 5,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'post_purchase_followup',
    category: 'vendite',
    icon: '🔁',
    nameIT: 'Follow-up post-acquisto',
    descriptionIT: 'Per ordini click & collect: messaggio dopo il ritiro per chiedere se va tutto bene.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'dynamic_pricing_widget',
    category: 'vendite',
    icon: '💡',
    nameIT: 'Widget prezzi dinamici',
    descriptionIT: 'Prezzi dal database invece che hardcoded. Già attivo.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'customer_onboarding',
    category: 'vendite',
    icon: '⚙️',
    nameIT: 'Onboarding cliente al primo login',
    descriptionIT: 'Wizard 90 secondi al primo accesso /profilo: nome, telefono, **compleanno** (sblocca campagna #4), consensi GDPR, foto profilo opzionale, preferenze taglio. Step skippabili. Re-prompt soft dopo 3 visite per i campi vuoti.',
    benefitIT: 'Foundation per TUTTE le campagne mirate — senza dati cliente niente funziona',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['birthday_campaign', 'gdpr_consents', 'customer_segments'],
    status: 'recommended',
  },

  // ─── Integrazioni ────────────────────────────────────────────────────
  {
    key: 'fatture_in_cloud',
    category: 'integrazioni',
    icon: '🧾',
    nameIT: 'Fatture in Cloud',
    descriptionIT: 'Genera automaticamente fatture/ricevute per ogni transazione. API gratuita.',
    effortHours: 10,
    monthlyCostEur: 4,
    requiresAccount: ['Fatture in Cloud'],
    status: 'available',
  },
  {
    key: 'data_backup_export',
    category: 'integrazioni',
    icon: '💾',
    nameIT: 'Backup & export dati',
    descriptionIT: 'Backup automatici Supabase + esportazione CSV da admin. Già attivo a livello DB; UI export in piano.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'google_hours_sync',
    category: 'integrazioni',
    icon: '🕑',
    nameIT: 'Sync orari Google Business',
    descriptionIT: 'Quando aggiorni orari o chiusure straordinarie nel gestionale, il profilo Google Business si aggiorna automaticamente. Zero clienti che arrivano per trovare chiuso = zero recensioni negative.',
    effortHours: 8,
    monthlyCostEur: 0,
    requiresAccount: ['Google Business Profile'],
    status: 'recommended',
  },
  {
    key: 'seo_position_tracker',
    category: 'integrazioni',
    icon: '📌',
    nameIT: 'Tracker posizione SEO',
    descriptionIT: 'Monitora posizione su Google per keyword chiave. Tool esterni (Ahrefs, Semrush, Search Console) fanno gratis lo stesso.',
    effortHours: 10,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'apple_maps_integration',
    category: 'integrazioni',
    icon: '🗺️',
    nameIT: 'Integrazione Apple Maps',
    descriptionIT: 'Apple Maps non ha API pubbliche per piccoli business.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'pos_payments',
    category: 'integrazioni',
    icon: '💳',
    nameIT: 'Pagamenti POS',
    descriptionIT: 'Stripe Terminal o SumUp webhook per registrare automaticamente i pagamenti POS.',
    effortHours: 14,
    monthlyCostEur: 0,
    requiresAccount: ['Stripe / SumUp'],
    status: 'available',
  },
  {
    key: 'uptime_monitoring',
    category: 'integrazioni',
    icon: '📡',
    nameIT: 'Monitoraggio uptime sito',
    descriptionIT: 'UptimeRobot, Better Stack fanno gratis quello che serve.',
    effortHours: 2,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'qr_promotions',
    category: 'integrazioni',
    icon: '📄',
    nameIT: 'Promozioni con QR code',
    descriptionIT: 'Genera QR univoci stampabili per coupon fisici (volantini, cartoline, vetrina di bar/palestre/hotel). Ogni QR è un coupon con UTM tracking → vedi quante prenotazioni vengono dal volantino X vs Y.',
    effortHours: 6,
    monthlyCostEur: 0,
    relatedSkills: ['coupons', 'utm_tracking'],
    status: 'recommended',
  },
  {
    key: 'salon_tv_dashboard',
    category: 'integrazioni',
    icon: '📺',
    nameIT: 'Dashboard TV in salone',
    descriptionIT: 'Schermo in sala d\'attesa con prossimi appuntamenti. Overkill per 2-chair.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'shipping_courier',
    category: 'integrazioni',
    icon: '📦',
    nameIT: 'Integrazione corriere',
    descriptionIT: 'Per spedizioni prodotti. Hair Rich fa solo click & collect, non spedisce.',
    effortHours: 12,
    monthlyCostEur: 5,
    status: 'not_recommended',
  },

  // ─── Gestione Avanzata ───────────────────────────────────────────────
  {
    key: 'multilingual_assistant',
    category: 'avanzata',
    icon: '🌍',
    nameIT: 'Assistente multilingua',
    descriptionIT: 'Sito già i18n (it/en/fr/de). Chatbot multilingua aggiuntivo è opzionale.',
    effortHours: 6,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'multi_location',
    category: 'avanzata',
    icon: '🏢',
    nameIT: 'Multi-sede',
    descriptionIT: 'Hair Rich ha un solo salone. Overkill.',
    effortHours: 40,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'multi_location_price_sync',
    category: 'avanzata',
    icon: '🔄',
    nameIT: 'Sync prezzi multi-sede',
    descriptionIT: 'Dipendente da multi-sede. N/A.',
    effortHours: 8,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'staff_contracts',
    category: 'avanzata',
    icon: '📜',
    nameIT: 'Gestione contratti staff',
    descriptionIT: 'HR avanzato, fuori scope.',
    effortHours: 20,
    monthlyCostEur: 0,
    status: 'not_recommended',
  },
  {
    key: 'proforma_invoice',
    category: 'avanzata',
    icon: '📄',
    nameIT: 'Fatture proforma',
    descriptionIT: 'Utile se entrano clienti B2B (hotel, yacht charter). Generatore di proforma PDF.',
    effortHours: 6,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'customer_access_report',
    category: 'avanzata',
    icon: '📊',
    nameIT: 'Report accessi clienti',
    descriptionIT: 'Statistiche su quando i clienti accedono al sito. GA4 fa già il 90%.',
    effortHours: 4,
    monthlyCostEur: 0,
    status: 'available',
  },
  {
    key: 'admin_inbox',
    category: 'avanzata',
    icon: '🔔',
    nameIT: 'Inbox notifiche admin',
    descriptionIT: 'Unica inbox centralizzata in cima a /admin (badge counter unread in sidebar). Ogni evento operativo (nuove prenotazioni, cancellazioni, no-show, recensioni, scorte basse, alert calo, scadenze pacchetti) entra qui. Archivable, filterable, realtime.',
    benefitIT: 'Un solo posto per vedere tutto invece di sparsi Telegram/email',
    effortHours: 10,
    monthlyCostEur: 0,
    relatedSkills: ['telegram_owner_alerts', 'activity_log'],
    status: 'recommended',
    alwaysOn: true,
  },
  {
    key: 'structured_feedback',
    category: 'avanzata',
    icon: '🔁',
    nameIT: 'Feedback strutturato per servizio',
    descriptionIT: 'Variante di post_visit_survey con scale numeriche e analisi per servizio.',
    effortHours: 8,
    monthlyCostEur: 0,
    relatedSkills: ['post_visit_survey'],
    status: 'available',
  },
  {
    key: 'appointments_audit_trail',
    category: 'avanzata',
    icon: '🗂️',
    nameIT: 'Audit trail appuntamenti',
    descriptionIT: 'Variante focalizzata di activity_log solo per appointments. Già coperta dal log generale.',
    effortHours: 2,
    monthlyCostEur: 0,
    relatedSkills: ['activity_log'],
    status: 'available',
  },
  {
    key: 'customer_pwa',
    category: 'avanzata',
    icon: '📱',
    nameIT: 'App cliente PWA',
    descriptionIT: 'Il sito è già installabile come PWA — funziona come app nativa.',
    effortHours: 0,
    monthlyCostEur: 0,
    status: 'recommended',
  },
  {
    key: 'advanced_customer_search',
    category: 'avanzata',
    icon: '🔍',
    nameIT: 'Ricerca avanzata clienti',
    descriptionIT: 'Query builder visuale per filtri concatenabili: segmento, servizio, operatore, # visite, spesa totale, ultima visita, no-show, compleanno, source, coupon, pacchetto, indirizzo, età, lingua. Salva ricerche con nome. Azioni batch (msg via Router, segmento manuale, coupon mirato, export CSV).',
    exampleIT: '"Clienti VIP con compleanno questo mese che non vengono da 60+ giorni" → 12 risultati → batch coupon -20%.',
    effortHours: 14,
    monthlyCostEur: 0,
    relatedSkills: ['customer_segments', 'coupons'],
    status: 'recommended',
  },
];

export function getSkill(key: string): Skill | undefined {
  return SKILLS.find((s) => s.key === key);
}

export function skillsByCategory(): Map<SkillCategory, Skill[]> {
  const map = new Map<SkillCategory, Skill[]>();
  for (const s of SKILLS) {
    if (!map.has(s.category)) map.set(s.category, []);
    map.get(s.category)!.push(s);
  }
  return map;
}

export const CATEGORY_LABELS: Record<SkillCategory, string> = {
  comunicazione: 'Comunicazione',
  booking: 'Prenotazione',
  ai: 'AI',
  analytics: 'Analytics',
  clienti: 'Clienti',
  team: 'Team',
  marketing: 'Marketing',
  vendite: 'Vendite',
  integrazioni: 'Integrazioni',
  avanzata: 'Avanzata',
};

export const STATUS_LABELS: Record<SkillStatus, string> = {
  recommended: 'Consigliata',
  available: 'Disponibile',
  in_development: 'In sviluppo',
  not_recommended: 'Non consigliata',
};
